Enable config of tfstate location
XenitAB/github-actions pull request #32
Opened 2021-09-22 11:47 UTC by NissesSenap

Solves #31, the user can now define
RG_LOCATION_LONG & RG_LOCATION_SHORT to overwrite the default tfstate location
westeurope & we.

2021-09-22 15:23 UTC, simongottschlag requested changes
I think this change could be much smaller. Pass the variables to the env file if and then use `VAR=${VAR:-default}` in the script.

Let us take a look at it together tomorrow!

2021-09-23 07:24 UTC, NissesSenap commented
I have verified that it works to update the value as suggested in the makefile, but you can also ignore it and use the default values.
I'm running plan on a existing env and I tried to change RG_LOCATION_LONG but I don't know how much terraform uses it so that's why I think it still works even if I write something like

```
RG_LOCATION_SHORT=we
RG_LOCATION_LONG=foo
```

2021-09-23 07:42 UTC, bittrance reviewed
I think it is somewhat confusing that some parameters are passed via command line and others are passed via environment variables. For me, the change to the readme above is illustrates why this approach is problematic. I think it is time for `terraform.sh` to grow proper `getopts`,

2021-09-23 07:43 UTC, bittrance commented on docker/terraform.sh
> -ENVIRONMENT_FILE="/tmp/${ENVIRONMENT}.env"
:+1:

2021-09-23 08:51 UTC, simongottschlag approved these changes
I've added a few comments that I would like to be fixed, after that feel free to merge! Good job! :)

2021-09-23 08:51 UTC, simongottschlag commented on README.md
> +DOCKER_RUN:=docker run --user $(shell id -u) $(TTY_OPTIONS) --rm --entrypoint /opt/terraform.sh --env-file $(TEMP_ENV_FILE) $(AZURE_DIR_MOUNT) -v $${PWD}/$(DIR):/tmp/$(DIR) -v $${PWD}/global.tfvars:/
Either a separate PR or at least update the PR description to explain why this is done.

2021-09-23 08:51 UTC, simongottschlag commented on README.md
> +	echo "RG_LOCATION_LONG=$(RG_LOCATION_LONG)" >> $(TEMP_ENV_FILE)
Looking at the other configurations, we don't enclose the text in `"` on the other places.

2021-09-23 14:12 UTC, merged